return {
    ["Greetings"] = {
        ["Hello"] = {
            "Hello",
            "Hey",
            "Greetings",
            "Yo",
            "Welcome",
            "What's up?",
            "Chat Wheel Guide", -- special config - do not remove
        },
        ["Goodbye"] = {
            "Bye",
            "See you",
            "Stay safe",
            "Good luck",
            "Take care",
            "I'm leaving",
            "Signing off",
        },
        ["Courtesy"] = {
            "Please",
            "Thank you",
            "Excuse me",
            "Sorry",
            "Apologies",
            "You're welcome",
            "No worries",
        },
        ["Radio"] = {
            "Copy that",
            "Say again",
            "Over and out",
            "Roger that",
            "Clear comms",
            "Hotmic",
        },
        ["Formal"] = {
            "Orders received",
            "Permission to speak",
            "Yes, sir",
            "No, sir",
            "At your service",
            "Standing by",
            "Acknowledged",
        },
        ["Friendly Banter"] = {
            "LOL",
            "Haha",
            "🤣",
            "😭",
            "Bruh",
            "Nice",
            "That was close",
        },
        ["Team Spirit"] = {
            "Stay together",
            "Watch your back",
            "Don't panic",
            "You got this",
            "Good luck",
            "We've got this",
            "Good job!",
        },
    },

    ["Commands"] = {
        ["Movement"] = {
            "Follow me!",
            "Stay behind me!",
            "Move out!",
            "Regroup here!",
            "Rally here!",
            "Come here!",
            "Leave!",
        },
        ["Formations"] = {
            "Wedge!",
            "Single file!",
            "Double column!",
            "Shoulder to shoulder!",
            "Strike formation!",
            "Firing line!",
        },
        ["Defense"] = {
            "Stay here!",
            "Hold position!",
            "Cover me!",
            "Secure this room!",
            "Block off that door!",
        },
        ["Combat"] = {
            "Hostile ahead!",
            "Hostile!",
            "Terminate target!",
            "Stop right there!",
            "Fall back!",
            "Cease fire!",
            "Reloading!",
        },
        ["Medical"] = {
            "Medic!",
            "I need heals!",
            "Heal them!",
            "Cover the medic!",
            "Checkup requested!",
            "+",
            ["BioBoost/ReVolt"] = {
                "Need Blue/Defence!",
                "Need Purple/Damage!",
                "Need Pink/Regen!",
                "Need Red/Health!",
                "Stim me!",
                "Stop stim!",
            },
        },
        ["Security"] = {
            "Present ID, and state if armed.",
            "Detain them.",
            "Do not enter this area.",
            "Do not go further!",
            "Stand down!",
            "Keep distance.",
        },
        ["Testing"] = {
            "I want a test!",
            "Follow me, Class-D.",
            "Begin test.",
            "Test completed.",
            "Test failed.",
            "Place Class-D inside chamber.",
            "Testing Brief", -- special config - do not remove
        },
    },

    ["Exclamations"] = {
        ["Danger"] = {
            "Run!",
            "They're coming!",
            "Take cover!",
            "Back up!",
            "Uh-oh!",
            "Don't do that!",
            "Stop!",
        },
        ["Incoming"] = {
            "Incoming!",
            "SCP spotted!",
            "Enemy ahead!",
            "Hostiles ahead!",
            "Combatives ahead!",
        },
        ["Urgency"] = {
            "Quickly!",
            "Now!",
            "Move!",
            "Hurry!",
            "Let's go!",
            "Hold up!",
        },
        ["Surprise"] = {
            "What?!",
            "No way!",
            "Wait!",
            "Bruh!",
            "Really?",
            "Wow!",
            "Nice!",
        },
        ["Success"] = {
            "Target down!",
            "Area secured!",
            "All clear!",
            "Good job!",
            "Nice work!",
        },
        ["Failure"] = {
            "Need help!",
            "Need backup!",
            "We're losing!",,
        },
    },

    ["Locations"] = {
        "CDCZ",
        "CDCZ VA",
        ["Sublevels"] = {
            "Topzone",
            "Sublevel 1",
            "Sublevel 2",
            "Sublevel 3",
            "Sublevel 4",
        },
        "Main Gate",
        "Topzone",
        "Control Room",
        ["Containment"] = {
            "Viewing Area",
            "Outer Containment Zone",
            "Inner Containment Zone",
        },
    },

    ["Responses"] = {
        ["Positive"] = {
            "Yes",
            "Affirmative",
            "Absolutely",
            "Definitely",
            "Of course",
            "Sure thing",
            "Roger",
        },
        ["Negative"] = {
            "No",
            "Negative",
            "Not at all",
            "Absolutely not",
            "No way",
            "I don't think so",
            "Denied",
        },
        ["Uncertain"] = {
            "Maybe",
            "Possibly",
            "Perhaps",
            "I guess",
            "Could be",
            "It's unclear",
            "Unsure",
        },
        ["Acknowledgement"] = {
            "Understood",
            "Got it",
            "Copy that",
            "Loud and clear",
            "Noted",
            "Acknowledged",
            "Received",
        },
        ["Courtesy"] = {
            "Please",
            "Thank you",
            "Excuse me",
            "Sorry",
            "Apologies",
            "You're welcome",
            "No worries",
        },
        ["Quick Emotes"] = {
            "Good",
            "Bad",
            "Nice",
            "Oops",
            "LOL",
            "Bruh",
            "Let's go",
        },
    },

    -- all scps from anomalous entity database excluding SCP-???
    ["SCPs"] = {
        ["000-035"] = {
            "SCP-001-J",
            "SCP-008",
            "SCP-009",
            "SCP-017",
            "SCP-023",
            "SCP-035",
        },
        ["036-099"] = {
            "SCP-049",
            "SCP-058",
            "SCP-076",
            "SCP-096",
        },
        ["100-399"] = {
            "SCP-106",
            "SCP-122",
            "SCP-123",
            "SCP-173",
            "SCP-178",
            "SCP-294",
            "SCP-352",
        },
        ["200-899"] = {
            "SCP-409",
            "SCP-457",
            "SCP-504",
            "SCP-527",
            "SCP-662",
            "SCP-682",
        },
        ["900-1499"] = {
            "SCP-914",
            "SCP-939",
            "SCP-966",
            "SCP-999",
            "SCP-1162",
            "SCP-1139",
            "SCP-1499",
        },
        ["1500-9999"] = {
            "SCP-2123-R",
            "SCP-2521",
            "SCP-4040",
        },
    },

    ["Teams"] = {
        "Hostile",
        "Friendly",
        ["Combative"] = {
            "Security Department",
            "Mobile Task Forces",
            "Foreign Outsourcing",
            "Chaos Insurgency",
            "Foreign Raiders",
        },
        ["Civil"] = {
            "Scientific Department",
            "Ethics Committee",
            "External Affairs",
            "Facility Maintenance",
            "Admissions Commitee",
        },
        ["Specialized/No Level"] = {
            "Administrative Department",
            "Manufacturing Department",
            "Roleplay Actors",
            "Department of Intelligence",
        },
        ["Level"] = {
            "Level 0",
            "Level 1",
            "Level 2",
            "Level 3",
            "Level 4",
            "Level 5",
            "OMNI",
        },
    },
}
