return {
    ["Greetings"] = {
        ["Hello"] = {
            "Hello",
            "Hey",
            "Greetings",
            "Yo",
            "Welcome",
            "What's up?",
            "Chat Wheel Guide", -- special config - do not remove
        },
        ["Goodbye"] = {
            "Bye",
            "See you",
            "Stay safe",
            "Good luck",
            "Take care",
            "I'm leaving",
            "Signing off",
        },
        ["Courtesy"] = {
            "Please",
            "Thank you",
            "Appreciate it",
            "Excuse me",
            "Sorry",
            "You're welcome",
            "No worries",
        },
        ["Radio"] = {
            "Copy that",
            "Loud and clear",
            "Say again",
            "Comms up",
            "Comms down",
            "Over and out",
            "Roger that",
        },
        ["Formal"] = {
            "Reporting in",
            "Orders received",
            "Permission to speak",
            "Yes, sir",
            "At your service",
            "Standing by",
            "Acknowledged",
        },
        ["Friendly Banter"] = {
            "LOL",
            "Haha",
            "XD",
            "🤣",
            "Bruh",
            "Nice",
            "That was close",
        },
        ["Team Spirit"] = {
            "Stay together",
            "Watch your back",
            "Don't panic",
            "You got this",
            "Good luck",
            "We've got this",
            "Good job!",
        },
    },

    ["Commands"] = {
        ["Movement"] = {
            "Follow me!",
            "Stay behind me!",
            "Move out!",
            "Regroup here!",
            "Come here!",
            "Go!",
            "Leave!",
        },
        ["Defense"] = {
            "Stay here!",
            "Hold position!",
            "Guard me!",
            "Cover me!",
            "Secure this room!",
            "Raise shields!",
            "Protect the Vault!",
        },
        ["Combat"] = {
            "Hostile ahead!",
            "Hostile spotted!",
            "Engage hostiles!",
            "Terminate target!",
            "Stop right there!",
            "Fall back!",
            "Cease fire!",
        },
        ["Medical"] = {
            "Medic!",
            "I need heal!",
            "I'm injured!",
            "Heal them!",
            "Cover the medic!",
            "Checkup requested!",
            "+",
        },
        ["Security"] = {
            "Show your ID!",
            "Can I see your ID?",
            "Detain them!",
            "Search them!",
            "Keep distance!",
            "Do not go further!",
            "Stand down!",
        },
        ["Testing"] = {
            "I want a test!",
            "Do you want a test?",
            "Begin test",
            "Test completed",
            "Move to Chamber",
            "Keep it contained",
            "Testing Brief", -- special config - do not remove
        },
        ["Orders/Admin"] = {
            ["Detain Zone"] = {
                "DZ Active",
                "DZ Inactive",
                "DZ Whitelist",
                "DZ Blacklist",
                "DZ 3 Studs",
                "DZ 5 Studs",
                "DZ Clear",
            },
            "Authorized Only",
            "Evacuate Area",
            "Room Locked",
            "Impeach",
            "Vote Kick",
            "Fire",
        },
    },

    ["Exclamations"] = {
        ["Danger"] = {
            "Run!",
            "They're coming!",
            "Take cover!",
            "Back up!",
            "Uh-oh!",
            "Don't do that!",
            "Stop!",
        },
        ["Incoming"] = {
            "Incoming!",
            "CI approaching!",
            "SCP spotted!",
            "Enemy ahead!",
            "Hostiles ahead!",
            "Combatives ahead!",
        },
        ["Urgency"] = {
            "Quickly!",
            "Now!",
            "Move!",
            "Hurry!",
            "Let's go!",
            "Go go go!",
            "Hold up!",
        },
        ["Surprise"] = {
            "What?!",
            "No way!",
            "Wait!",
            "Bruh!",
            "Really?",
            "Wow!",
            "Nice!",
        },
        ["Success"] = {
            "Target is down!",
            "Area secured!",
            "All clear!",
            "Good job!",
            "Nice work!",
            "Mission complete!",
            "We did it!",
        },
        ["Failure"] = {
            "I'm down!",
            "Need help!",
            "Need backup!",
            "We're losing!",
            "Out of ammo!",
            "Mission failed!",
            "Abort!",
        },
    },

    ["Locations"] = {
        "CDC",
        ["Sector"] = {
            "Sector 1",
            "Sector 2",
            "Sector 3",
            "Sector 4",
            "REDACTED Sector",
        },
        ["Gate/Outside"] = {
            "Gate A",
            "Gate B",
            "Outside",
        },
        "Vault",
        "Warheads",
        "Control Room",
        "Chamber",
    },

    ["Responses"] = {
        ["Positive"] = {
            "Yes",
            "Affirmative",
            "Absolutely",
            "Definitely",
            "Of course",
            "Sure thing",
            "Roger",
        },
        ["Negative"] = {
            "No",
            "Negative",
            "Not at all",
            "Absolutely not",
            "No way",
            "I don't think so",
            "Denied",
        },
        ["Uncertain"] = {
            "Maybe",
            "Not sure",
            "Possibly",
            "I guess",
            "Could be",
            "It's unclear",
            "Unsure",
        },
        ["Acknowledgement"] = {
            "Understood",
            "Got it",
            "Copy that",
            "Loud and clear",
            "Noted",
            "Acknowledged",
            "Received",
        },
        ["Courtesy"] = {
            "Please",
            "Thank you",
            "Appreciate it",
            "Excuse me",
            "Sorry",
            "You're welcome",
            "No worries",
        },
        ["Quick Emotes"] = {
            "Good",
            "Bad",
            "Nice",
            "Oops",
            "LOL",
            "Bruh",
            "Let's go",
        },
    },

    ["SCPs"] = {
        ["000-099"] = {
            "SCP-001-J",
            "SCP-008",
            "SCP-009",
            "SCP-017",
            "SCP-035",
            "SCP-049",
            "SCP-096",
        },
        ["100-399"] = {
            "SCP-106",
            "SCP-122",
            "SCP-173",
            "SCP-178",
            "SCP-294",
            "SCP-352",
        },
        ["200-899"] = {
            "SCP-409",
            "SCP-426",
            "SCP-457",
            "SCP-504",
            "SCP-682",
        },
        ["900-1499"] = {
            "SCP-914",
            "SCP-939",
            "SCP-966",
            "SCP-999",
            "SCP-1162",
            "SCP-1499",
            "SCP-1499",
        },
        ["1500-9999"] = {
            "SCP-2123",
            "SCP-2521",
            "SCP-4040",
        },
    },

    ["Teams"] = {
        "Hostile",
        "Friendly",
        ["Combative"] = {
            "Security Department",
            "Mobile Task Force",
            "Rapid Response Team",
            "Global Occult Coalition",
            "Chaos Insurgency",
        },
        ["Civil"] = {
            "Scientific Department",
            "Medical Department",
            "Ethics Committee",
            "Engineering & Technical",
            "Administrative Department",
            "External Affairs",
        },
        ["Redacted"] = {
            "Internal Security Department",
            "Intelligence Agency",
            "Rapid Response Team",
        },
        ["Roleplay"] = {
            "The Administrator",
            "O5 Council",
            "Site Director",
            "Secretary",
            "Coalition Director",
        },
        ["Level"] = {
            "Level 1",
            "Level 2",
            "Level 3",
            "Level 4",
            "Level 5",
            "REDACTED",
            "OMNI",
        },
    },
}
